### ISSUE TITLE
[#0101] Captura de dados

### ISSUE THREAD

**Issue by GabrielCamargoL** [The-Bugger-Ducks/mood-hound-nlp#1]
## Descrição da atividade

Implementar um pipeline de coleta de dados para capturar comentários de clientes: https://raw.githubusercontent.com/americanas-tech/b2w-reviews01/main/B2W-Reviews01.csv

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente

## DoD

- [x] Code review
- [x] Testado e integrado
- [x] Documentado
- [x] Aceito pelo PO

**Comment by MariaGabrielaReis** [comment]
# Captura de dados

Nessa task foi desenvolvido a função que faz a leitura dos dados necessários.

- CSV lido: [B2W reviews](https://raw.githubusercontent.com/americanas-tech/b2w-reviews01/main/B2W-Reviews01.csv)

## Resultado 

![Image](https://github.com/The-Bugger-Ducks/mood-hound-nlp/assets/69374340/f7d3e645-2f2e-4f2d-9442-d7a01704af56)
