### ISSUE TITLE
[#0011] Melhoria: implementar novo modelo de rastreio de tempo na pipeline PLN

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/mood-hound-nlp#18]

**Comment by ThHenrique** [comment]
?

**Comment by ThHenrique** [comment]
@drisabelles

**Comment by drisabelles** [comment]
@ThHenrique a @MariaGabrielaReis pediu para que essa melhoria fosse adicionada, não tenho mais detalhes sobre ela porque ela havia me falado que iria fazer. Pode nos informar melhor sobre os detalhes, Maria?

**Comment by drisabelles** [comment]
@ThHenrique @MariaGabrielaReis foi entendido que essa task será levada para a próxima sprint
