### ISSUE TITLE
[#0102] Limpeza de dados - geral

### ISSUE THREAD

**Issue by GabrielCamargoL** [The-Bugger-Ducks/mood-hound-nlp#2]
## Descrição da atividade

Implementar um pipeline de limpeza e organização de dados para preparar os comentários para análise
https://raw.githubusercontent.com/americanas-tech/b2w-reviews01/main/B2W-Reviews01.csv

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente

## DoD

- [x] Code review
- [x] Testado e integrado
- [x] Documentado
- [x] Aceito pelo PO

**Comment by MariaGabrielaReis** [comment]
# Limpeza de dados

Nessa task foi desenvolvido a parte do processo que organiza os dados necessários, além de funções para geração de prints no código (de cada fase desse processo) e para contagem do intervalo entre a execução de uma função e outra.

- Análise exploratória e adaptações: 
   - Remoção dos comentários nulos;
   - Comentários com menos de 3 caracteres;
   - Registros duplicados;
   - Formatação da coluna `submission_date` (data da review);
   - Remoção de colunas desnecessárias no momento;

## Resultado 

![Image](https://github.com/The-Bugger-Ducks/mood-hound-nlp/assets/69374340/f7d3e645-2f2e-4f2d-9442-d7a01704af56)
