### ISSUE TITLE
[#0035] Refatoração: aplicar caixa alta no texto de sentimento

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/mood-hound-nlp#23]
Atualmente as palavras sobre os sentimentos estão sendo escritas como **"Positivo"**, temos alterar para que sejam escritas como **"POSITIVO"**.

**Comment by MariaGabrielaReis** [comment]
# Capitalize sentiments

Capitalização do mapeamento de sentimentos (de "Positivo, Neutro e Negativo" para "POSITIVO, NEGATIVO e NEUTRO")

**Comment by drisabelles** [comment]
@GabrielCamargoL 

- [x] Aprovado pelo P.O
