### ISSUE TITLE
[#0301] Análise de sentimentos

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/mood-hound-nlp#26]
## Descrição da atividade

- Pesquisa de Analise de sentimentos por texto.

## Informações para execução da atividade

- Verificar se há como medir o sentimento por texto (não precisa associar com estrelas por enquanto). Caso seja possível e com os tenha orientação do professor fabricio, novas tasks sobre o assunto serão geradas.

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente
- [ ] Prototipado

## DoD

- [ ] Code review
- [ ] Testado e integrado
- [ ] Documentado
- [ ] Aceito pelo PO

**Comment by MariaGabrielaReis** [comment]
https://github.com/fabriciogmc/natural_language_processing/blob/main/python/nlp_classification/simple_bow_knn_scikit.py

**Comment by MariaGabrielaReis** [comment]
Traduzir para inglês os sentimentos

**Comment by drisabelles** [comment]
A partir dessa task foram levantadas as seguintes tasks: 

- separar amostra das reviews para treinamento do modelo

- criar modelo de classificação utilizando KNN

- treinar modelo para levantamento de estatísticas (acurácia, precisão e matriz de confusão) 

- integrar modelo de classificação na pipeline
