### ISSUE TITLE
[#0044] Refatoração: colocar os atributos, temas e sentimentos em língua portuguesa

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/mood-hound-nlp#29]
Código PLN: 
```python
labels = { 
      0:'QUALITY', 
      1:'RECEIVEMENT', 
      2:'DELIVERY', 
      3:'DELIVERY', 
      4:'EXPECTATION',
      5:'OTHERS', 
      6:'SATISFIED', 
      7:'COSTBENEFIT',
      8:'RECOMMENDATION',
      9:'DELIVERY'
  }
```

**Comment by drisabelles** [comment]
@MariaGabrielaReis @JoaoM-py fui informada pelo @ThHenrique que precisamos dessa taks no nlp.

**Comment by MariaGabrielaReis** [comment]
Para tal atividade, os tópicos e sentimentos foram traduzidos do inglês para o português, como nas evidências abaixo:

- **SENTIMENTOS**

| Antes                                 | Depois                           |
|:-----------------------------|:--------------------------|
|```ratings_maping = {5: 'POSITIVE', 4: 'POSITIVE', 3: 'NEUTRAL', 2: 'NEGATIVE', 1: 'NEGATIVE' } ``` | ```ratings_maping = { 5: 'POSITIVO', 4: 'POSITIVO', 3: 'NEUTRO', 2: 'NEGATIVO', 1: 'NEGATIVO' } ``` | 

- **TÓPICOS**

| Antes                                 | Depois                           |
|:-----------------------------|:--------------------------|
|``` labels = { 0:'QUALITY', 1:'RECEIVEMENT', 2:'DELIVERY', 3:'DELIVERY', 4:'EXPECTATION', 5:'OTHERS', 6:'SATISFIED', 7:'COSTBENEFIT', 8:'RECOMMENDATION', 9:'DELIVERY' }``` | ```labels = { 0:'QUALIDADE', 1:'RECEBIMENTO', 2:'ENTREGA', 3:'ENTREGA', 4:'EXPECTATIVA', 5:'OUTROS', 6:'SATISFAÇÃO', 7:'CUSTO BENEFÍCIO', 8:'RECOMENDAÇÃO', 9:'ENTREGA' }``` |

**Comment by drisabelles** [comment]
@GabrielCamargoL 

- [x] Aprovado pelo P.O
