### ISSUE TITLE
[#0103] Armazenamento de texto processado

### ISSUE THREAD

**Issue by GabrielCamargoL** [The-Bugger-Ducks/mood-hound-nlp#3]
## Descrição da atividade

Em um pipeline, execute o armazenamento de texto já processados para a execução de análise de tema e sentimentos.

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente

## DoD

- [x] Code review
- [x] Testado e integrado
- [x] Documentado
- [x] Aceito pelo PO

**Comment by MariaGabrielaReis** [comment]
# Armazenamento de dados processados #3 

Nessa task foi desenvolvido a função para cadastrar dados mockados pré-processados de uma tabela nlp.

-Modelo de dado utilizado:
``` 
        {
            'id': str(uuid.uuid4()),  
            'text': 'Bom material',
            'topic': 'Tópico A',
            'sentiment': 'Positivo',
            'rating': 4,
            'product_id': 'qb453yq5b',
            'product_name': 'Guarrafa',
            'created_at': '2020-11-11',  
            'added_at': str(datetime.now().timestamp())  
        },

```

## Resultado 

![image](https://github.com/The-Bugger-Ducks/mood-hound-nlp/assets/80930525/35ec7f7c-498a-4a07-8ab3-f0d2087c7bf3)
