### ISSUE TITLE
[#0201] Classificação de temas

### ISSUE THREAD

**Issue by GabrielCamargoL** [The-Bugger-Ducks/mood-hound-nlp#4]
## Descrição da atividade

Em um pipeline, categorizar os comentários em temas relacionados a: 
- ~~atributos de produtos~~ (vermelho, bonito, feio)
- ~~serviços~~ (pagamento, etc)
- ~~processos operacionais.~~ (rapido, entrega demorada)

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente

## DoD

- [x] Code review
- [x] Testado e integrado
- [x] Documentado
- [ ] Aceito pelo PO

**Comment by MariaGabrielaReis** [comment]
# [#0201] Classificação de temas

Criação de funções para cada passo do pipeline implementado que conta com:

1. Acesso aos dados
2. Limpeza dos dados (remoção de colunas desnecessárias)
3. Seleção de amostra
4. Processamento dos dados (pré-processamento, vetorização e classificação das reviews)
5. Visualização da distribuição do resultado pelos tópicos
6. Armazenamento do resultado em banco de dados

## Observações:
- Estamos trabalhando com uma amostra de 30 mil reviews, delas:
   - 10 mil são avaliações consideradas "positivas" (de 4 a 5 estrelas)
   - 10 mil são avaliações consideradas "neutras" (3 estrelas)
   - 10 mil são avaliações consideradas "negativas" (de 1 a 2 estrelas)
- Estamos levando em conta a classificação das reviews baseado em temas previamente listados, que são: **Qualidade, Recebimento, Entrega, Expectativa, Outros, Satisfação geral, Custo-benefício e Recomendação**. Por conta dessa escolha por tópicos fixos inicialmente, as chances do classificador de temas trocar o significado e a label do tema são grandes, ocasionando assim a classificação errônea dos dados. 
> Estes detalhes serão revisados nas próximas sprints

## Resultado da execução da pipeline:
<details>
   <summary>1. Acesso aos dados</summary>
  
<p align="center">
  <img src="https://github.com/The-Bugger-Ducks/mood-hound-nlp/assets/69374340/bdf92c3d-944b-4153-a464-985afc552635" width="100%" />
</p>
</details>
<details>
   <summary>2. Limpeza dos dados</summary>
  
<p align="center">
  <img src="https://github.com/The-Bugger-Ducks/mood-hound-nlp/assets/69374340/106c84b6-72df-4925-954e-1dbd50c7373f" width="100%" />
</p>
</details>
<details>
   <summary>3. Seleção de amostra</summary>
  
<p align="center">
  <img src="https://github.com/The-Bugger-Ducks/mood-hound-nlp/assets/69374340/9781c927-bf21-4356-a62b-bda260a4b4e8" width="100%" />
</p>
</details>
<details>
   <summary>4. Processamento dos dados</summary>
  
<p align="center">
  <img src="https://github.com/The-Bugger-Ducks/mood-hound-nlp/assets/69374340/e0c3e153-6fb2-4175-ac7e-639082af8c70" width="100%" />
</p>
</details>
<details>
   <summary>5. Visualização da distribuição do resultado pelos tópicos</summary>
  
<p align="center">
  <img src="https://github.com/The-Bugger-Ducks/mood-hound-nlp/assets/69374340/dcc1f629-c4a2-4b8b-9571-7b4ef478173d" width="100%" />
</p>
<p align="center">
  <img src="https://github.com/The-Bugger-Ducks/mood-hound-nlp/assets/69374340/cfe60a65-2016-4fb9-80e1-1c18490af7cc" width="100%" />
</p>
</details>
