### ISSUE TITLE
[#0051] Refatoração: melhorar a análise de sentimentos

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/mood-hound-nlp#42]
- Levar em consideração as reviews neutras;
- Tratar o desbalanceamento da base de dados (70% das reviews são positivas)

**Comment by MariaGabrielaReis** [comment]
## Refatoração: melhorar a análise de sentimentos

Essa tarefa consiste em aplicar alguns ajustes na pipeline visando melhorar a classificação de sentimento das avaliações:
- Adicionar o tipo de review "NEUTRA" no treinamento e na aplicação do modelo de análise de sentimento;
- Tratar o desbalanceamento da base de dados no treinamento;
- Trocar o uso do Bag of Words + TF-IDF + KNN por Word2Vec + Multilayer Perceptron;

### Adicionar o tipo de review "NEUTRA"
Como pode se ver nos trechos de código a seguir, tanto no treinamento quanto na pipeline em si foi levada em consideração agora as reviews com classificação "neutra" (que são baseadas em reviews com o total de 3 estrelas).

- Adição das reviews neutras no treinamento:
```py
def select_training_data(df):
    positive = random_select(21, df, 'POSITIVO', 33) # reviews positivas
    neutral = random_select(21, df, 'NEUTRO', 33) # reviews neutras
    negative = random_select(21, df, 'NEGATIVO', 34)  # reviews negativas
    select = np.concatenate([positive, neutral, negative])
    
    df = df[df['text'].isin(select)].reset_index(drop=True)
    df = df.sample(frac=1).reset_index(drop=True)
    
    return df
```

- Adição das reviews neutras na pipeline:
```py
def select_data(df):
    positive = random_select.select(100, df, 'POSITIVO', 28000) # máximo: 78210
    neutral = random_select.select(100, df, 'NEUTRO', 15834) # máximo de neutras
    negative = random_select.select(100, df, 'NEGATIVO', 28000) # máximo: 32594
    select = np.concatenate([positive, neutral, negative])
    
    df = df[df['text'].isin(select)].reset_index(drop=True)
    df = df.sample(frac=1).reset_index(drop=True)
    
    return df
```

### Tratar o desbalanceamento dos dados no treinamento
Como observado anteriormente, os dados da base disponibilizada tem uma proporção em torno de 70% positivas, 10% neutras e 20% negativas, onde, ao espelhar essa proporção no modelo de análise de sentimento, tivemos como resultado um modelo "viciado" em classificar reviews como positivas, então apesar de valores altos para acurácia e precisão, sua classificação estava equivocada. 

Identificado os problemas da antiga aplicação (utilizar a classificação antes do pré processamento dos dados e usar a proporção da base para o treino), as correções possíveis foram aplicadas:

- Aplicação de pré processamento no corpus ANTES da classificação das reviews:
```py
def processing(df, num_topics_default=7):
    # Limpeza dos dados e lematização
    print('- Limpeza dos dados e lematização...')
    dp = format_comments.DataPreparation()
    corpus = []
    for review in df['text']:
      result = dp.lemmatize(review)
      corpus.append(result[0])
    df['corpus'] = corpus
    print('Limpeza dos dados e lematização concluída ')

    # Análise de sentimentos
    print('-----------------------------------------------------------------------------')
    print('- Análise de sentimentos...')
    df = training_model.classification_model(df)
    print('Análise de sentimentos concluída')
```

- Utilização de uma proporção igualitária entre os sentimentos das reviews (para evitar vício de reviews positivas):
```py
def select_data(df):
    positive = random_select(100, df, 'POSITIVO', 33) # 33/100 reviews positivas
    neutral = random_select(100, df, 'NEUTRO', 33) # 33/100 reviews neutras
    negative = random_select(100, df, 'NEGATIVO', 34)  # 34/100 reviews negativas
    select = np.concatenate([positive, neutral, negative])
    
    df = df[df['text'].isin(select)].reset_index(drop=True)
    df = df.sample(frac=1).reset_index(drop=True)
    
    return df
```

### Substituição das técnicas utilizadas na análise de sentimento
A aplicação anterior da pipeline utilizava das técnicas de Bag of Words , TF-IDF e KNN para classificação dos sentimentos. Após estudos, optamos por substituir essas técnicas pelo modelo do Word2Vec aliado ao Multilayer Perceptron, visando melhorar a performance da análise de sentimento.

```py
# =============================================================================
# Aplicação do modelo
def classification_model(data):
    # ... transformação dos dadosdf = select_data(data)

    # uso do Word2Vec com os dados pré processados
    w2v_model = use_word2vec(data['corpus'])

    # ... treinamento do modelo
    w2v_train_df = pd.DataFrame(np.array(doc_embeddings_train))

    # ... aplicação do modelo
    w2v_df = pd.DataFrame(np.array(doc_embeddings))

    y_train = train_data.iloc[:, -1]

    # uso do Multilayer Perceptron
    mlp = MLPClassifier(hidden_layer_sizes=(100, 50, 10), random_state=7, max_iter=10000)
    mlp.fit(w2v_train_df, y_train)
    w2v_predict = mlp.predict(w2v_df)

    data['sentiment'] = w2v_predict

    return data
```
