### ISSUE TITLE
[#0050] Refatoração: aumentar a quantidade de reviews sendo processadas

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/mood-hound-nlp#43]

**Comment by MariaGabrielaReis** [comment]
## Refatoração: aumentar a quantidade de reviews sendo processadas

Essa tarefa consiste em aumentar o número de reviews que a pipeline consegue processar. Na sprint anterior estávamos trabalhando com um total de 6 mil reviews no processamento (3 mil positivas e 3 mil negativas), porém, nessa sprint, aumentamos a quantidade para um total de 71 mil reviews, sendo pouco mais de 15 mil neutras, 28 mil positivas e 28 mil negativas, totalizando um tempo de pipeline de cerca de 33 minutos.

```py
# ANTES
def select_data(df):
  positive = random_select.select(100, df, 'POSITIVO', 3000)
  negative = random_select.select(100, df, 'NEGATIVO', 3000)
  select = np.concatenate([positive, negative])


# DEPOIS
def select_data(df):
  positive = random_select.select(100, df, 'POSITIVO', 28000) # máximo: 78210
  neutral = random_select.select(100, df, 'NEUTRO', 15834) # máximo de neutras
  negative = random_select.select(100, df, 'NEGATIVO', 28000) # máximo: 32594
  select = np.concatenate([positive, neutral, negative])

```
