### ISSUE TITLE
[#0058] Melhorar a qualidade do código

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/mood-hound-nlp#54]
Trabalhar nas melhorias de:

- Clean code
- Code smells
- Testes

**Comment by MariaGabrielaReis** [comment]
# Otimizando passo 1 e 2: acesso e limpeza dos dados
Foi alterado o modo com que o acesso e limpeza dos dados acontecia.

### Antes
Carregávamos a base toda, limpávamos e depois removíamos as colunas que não seriam usada, Resultado da memória com esse acesso e limpeza antigos:
| Todos os dados carregados | Dados depois da limpeza |
| :------------------------------:|:----------------------------:|
| ![image](https://github.com/The-Bugger-Ducks/mood-hound-nlp/assets/69374340/109837ea-f807-421b-9c24-454a48d5ab40) | ![image](https://github.com/The-Bugger-Ducks/mood-hound-nlp/assets/69374340/fdf265c5-e8ee-417a-a04e-b6d9cfe92905) |

### Agora
Ao acessar os dados são selecionados apenas as colunas que são necessárias, também definindo os tipos dos dados (o tipo `object`do Python é o que ocupa mais espaço de memória), assim otimizando o tamanho da base trabalhada:

<div align="center">

![image](https://github.com/The-Bugger-Ducks/mood-hound-nlp/assets/69374340/25523756-0905-42fc-a406-ef47291839ad)
</div>

Dessa forma a otimização dos passos 1 e 2 da pipeline foram feitos, visando aumentar a performance e diminuir o tempo e/ou consumo de memória necessários para todo o processamento.

|                                                           |  Valor anterior | Valor atual |
|----------------------------------------:|:----------------:|:------------:|
| Quantidade de dados total               |      132.373      |   132.373    | 
| Quantidade de dados válidos           |      126.638      |   121.048    | 
| Variação                                             |         5.735       |     11.325    |
| Dados inválidos em relação ao total |       `4,33%`      |     `8,55%`   |

Essa mudança se deu por conta da remoção dos registros em que alguma das colunas tivessem valores nulos ou formato não apropriado. Anteriormente apenas era tratado a coluna do texto da avaliação, agora colunas como gênero, estado e ano de aniversário também são devidamente tratadas

---
# Otimizando passos 4 a 6 e extra: pré processamento, análise de sentimento, teste do modelo e modelagem de tópico

Foram criados novos arquivos para melhor organização dos passos da pipeline: um arquivo apenas para o modelo classificador e suas funções, outro arquivo exclusivo de pré processamento e um outro exclusivo para modelagem de tópicos, além de um arquivo separado na pasta `utils` para avaliar as métricas do modelo classificador (geração de métricas).

Refatorações e otimizações foram feitas no modelo, na formatação do código, organização de funções entre outras ações que permitiram que toda a base de dados fosse pré processada em um tempo médio de 9 a 12 minutos, como demonstrado na captura do terminal abaixo:

![image](https://github.com/The-Bugger-Ducks/mood-hound-nlp/assets/69374340/571d0f19-1d37-48a4-a815-919e16ff4e8f)

> **OBS.:** Após as refaforações e otimizações gerais será observado se ainda haverá a necessidade de aplicação da técnica de chunks e se existem outras formas de melhorar o modelo classificador de sentimento
