### ISSUE TITLE
[#0104] Formatação de comentario

### ISSUE THREAD

**Issue by GabrielCamargoL** [The-Bugger-Ducks/mood-hound-nlp#7]
## Descrição da atividade

- Formatar comentários para melhorar análise de classificação de temas e de sentimentos.

## Informações para execução da atividade

- Utilize, se viável, algorítmos como stemização e lemmatização, apresentados pelo professor Fabricio.

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente
- [x] Prototipado

## DoD

- [x] Code review
- [x] Testado e integrado
- [x] Documentado
- [x] Aceito pelo PO

**Comment by MariaGabrielaReis** [comment]
## Formatação de comentario
Foi criado uma classe para preparação dos dados contendo funções para limpeza e lematização dos dados, onde, utilizando-os, temos as seguintes saídas:

![image](https://github.com/The-Bugger-Ducks/mood-hound-nlp/assets/69374340/9df474c9-274e-4ba7-ac28-9735e5c0c2da)
![image](https://github.com/The-Bugger-Ducks/mood-hound-nlp/assets/69374340/ff228b5e-d8e1-4faa-aeb5-8c03c8f16943)
